main(){
    try {
        throw Error("test", 1, 2, 3);
    } catch (Error e) {
        print(e.message);
        print(e.args.get(0));
    }
}
