addOneToPositiveNum(x) {
    if(x < 0) {
        throw ArgumentError("Argument x cannot be negative. Value of x is: ", x);
    }
    elif(!(x is int)) {
        throw TypeError("Argument x must be of type int. Value of x is: ", x);
    }
    return x + 1;
}

main(){
    try {
        print(addOneToPositiveNum(-1));
    } catch {
        print("Something went wrong...");
    }

    try {
        print(addOneToPositiveNum(-1));
    } catch (Error e) {
        print("Something went wrong...");
        print("Error message: ", e?.message);
        print("Error arguments: ", e?.args);
    }

    try {
        print(addOneToPositiveNum(-1));
    } 
    catch (ArgumentError e) {
        if (e?.args?.get(0) is int) {
            print(addOneToPositiveNum(e?.args?.get(0) * -1));
        }
    }

    try {
        print(addOneToPositiveNum());
    } 
    catch (ArgumentError | TypeError e) {
        print("There was an error with arguments");
        print("Error message: ", e?.message);
        print("Error arguments: ", e?.args);
    }
}
